import Vue from 'vue'
import 'view-design/dist/styles/iview.css'
import notice from './notice'

import { Affix, Alert, Anchor, AnchorLink, AutoComplete, Avatar, BackTop, Badge, Breadcrumb, BreadcrumbItem, Button, ButtonGroup, Card, Carousel, CarouselItem, Cascader, Cell, CellGroup, Checkbox, CheckboxGroup, Col, Collapse, ColorPicker, Content, DatePicker, Divider, Drawer, Dropdown, DropdownItem, DropdownMenu, Footer, Form, FormItem, Header, Icon, Input, InputNumber, Scroll, Sider, Split, Submenu, Layout, LoadingBar, Menu, MenuGroup, MenuItem, Message, Modal, Notice, Option, OptionGroup, Page, Panel, Poptip, Progress, Radio, RadioGroup, Rate, Row, Select, Slider, Spin, Step, Steps, Table, Tabs, TabPane, Tag, Time, Timeline, TimelineItem, TimePicker, Tooltip, Transfer, Tree, Upload, Circle, Switch } from 'view-design'
Vue.component('Affix', Affix)
Vue.component('Alert', Alert)
Vue.component('Anchor', Anchor)
Vue.component('AnchorLink', AnchorLink)
Vue.component('AutoComplete', AutoComplete)
Vue.component('Avatar', Avatar)
Vue.component('BackTop', BackTop)
Vue.component('Badge', Badge)
Vue.component('Breadcrumb', Breadcrumb)
Vue.component('BreadcrumbItem', BreadcrumbItem)
Vue.component('Button', Button)
Vue.component('ButtonGroup', ButtonGroup)
Vue.component('Card', Card)
Vue.component('Carousel', Carousel)
Vue.component('CarouselItem', CarouselItem)
Vue.component('Cascader', Cascader)
Vue.component('Cell', Cell)
Vue.component('CellGroup', CellGroup)
Vue.component('Checkbox', Checkbox)
Vue.component('CheckboxGroup', CheckboxGroup)
Vue.component('Col', Col)
Vue.component('Collapse', Collapse)
Vue.component('ColorPicker', ColorPicker)
Vue.component('Content', Content)
Vue.component('DatePicker', DatePicker)
Vue.component('Divider', Divider)
Vue.component('Drawer', Drawer)
Vue.component('Dropdown', Dropdown)
Vue.component('DropdownItem', DropdownItem)
Vue.component('DropdownMenu', DropdownMenu)
Vue.component('Footer', Footer)
Vue.component('Form', Form)
Vue.component('FormItem', FormItem)
Vue.component('Header', Header)
Vue.component('Icon', Icon)
Vue.component('Input', Input)
Vue.component('InputNumber', InputNumber)
Vue.component('Scroll', Scroll)
Vue.component('Sider', Sider)
Vue.component('Split', Split)
Vue.component('Submenu', Submenu)
Vue.component('Layout', Layout)
// Vue.component('LoadingBar', LoadingBar)
Vue.component('Menu', Menu)
Vue.component('MenuGroup', MenuGroup)
Vue.component('MenuItem', MenuItem)
// Vue.component('Message', Message)
Vue.component('Modal', Modal)
// Vue.component('Notice', Notice)
Vue.component('Option', Option)
Vue.component('OptionGroup', OptionGroup)
Vue.component('Page', Page)
Vue.component('Panel', Panel)
Vue.component('Poptip', Poptip)
Vue.component('Progress', Progress)
Vue.component('Radio', Radio)
Vue.component('RadioGroup', RadioGroup)
Vue.component('Rate', Rate)
Vue.component('Row', Row)
Vue.component('Select', Select)
Vue.component('Slider', Slider)
Vue.component('Spin', Spin)
Vue.component('Step', Step)
Vue.component('Steps', Steps)
Vue.component('Table', Table)
Vue.component('Tabs', Tabs)
Vue.component('TabPane', TabPane)
Vue.component('Tag', Tag)
Vue.component('Time', Time)
Vue.component('Timeline', Timeline)
Vue.component('TimelineItem', TimelineItem)
Vue.component('TimePicker', TimePicker)
Vue.component('Tooltip', Tooltip)
Vue.component('Transfer', Transfer)
Vue.component('Tree', Tree)
Vue.component('Upload', Upload)

Vue.component('iButton', Button)
Vue.component('iCircle', Circle)
Vue.component('iCol', Col)
Vue.component('iContent', Content)
Vue.component('iForm', Form)
Vue.component('iFooter', Footer)
Vue.component('iHeader', Header)
Vue.component('iInput', Input)
Vue.component('iMenu', Menu)
Vue.component('iOption', Option)
Vue.component('iProgress', Progress)
Vue.component('iSelect', Select)
Vue.component('iSwitch', Switch)
Vue.component('iTable', Table)
Vue.component('iTime', Time)

Vue.prototype.$Loading = LoadingBar
Vue.prototype.$Message = Message
Vue.prototype.$Modal = Modal
Vue.prototype.$Notice = Notice
Vue.prototype.$Spin = Spin
Vue.prototype.$notice = Vue.$Notice = notice
Vue.prototype.errorMsg = msg => notice.error({ title: '错误', desc: msg })
Vue.prototype.warningMsg = msg => notice.warning({ title: '警告', desc: msg })
Vue.prototype.successMsg = msg => notice.success({ title: '成功', desc: msg, duration: 2 })
